# This configuration file is for the **development** setup.
# For a production example please refer to kubernetes or CloudRun setups
version: "3.9"
x-redash-service: &redash-service
  build:
    context: .
    cache_from:
      - "type=gha"
    cache_to:
      - "type=gha,mode=max"
    args:
      skip_frontend_build: "${skip_frontend_build-}"
      skip_dev_deps: "${skip_dev_deps-}"
      skip_ds_deps: "${skip_ds_deps-}"
  volumes:
    - .:/app
x-redash-environment: &redash-environment
  REDASH_LOG_LEVEL: "DEBUG"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  REDASH_RATELIMIT_ENABLED: false
  REDASH_MAIL_DEFAULT_SENDER: noreply@datareporter.com
  REDASH_AUTH_TYPE: "api_key"
  REDASH_MAIL_SERVER: "email"
  REDASH_MAIL_PORT: 1025
  REDASH_ENFORCE_CSRF: true
  MAILCHIMP_SERVER: "us1"
  MAILCHIMP_API_KEY: "e4c804be8fbd3c445a0fef9d05b6fc27"
  MAILCHIMP_LIST_ID: "e48180787b"
  REDASH_DEBUG: "true"
  CLIENT_TIMEOUT_DELTA: 100000
services:
  server:
    <<: *redash-service
    command: dev_server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
      - "5678:5678"
    environment:
      <<: *redash-environment
      REDASH_WORKER_NOTIFY_URL: "http://worker-server:5000/execute"
      PYTHONUNBUFFERED: 0
      PLYWOOD_SERVER_URL: "http://plywood:3000"
    volumes:
      - .:/app
  scheduler:
    <<: *redash-service
    command: dev_scheduler
    depends_on:
      - server
    environment:
      <<: *redash-environment
  worker-server:
    <<: *redash-service
    command: dev_worker_server
    ports:
      - "5001:5000"
      - "5679:5678"
    depends_on:
      - server
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379"
  postgres:
    image: pgautoupgrade/pgautoupgrade:latest
    ports:
      - "15432:5432"
      - "5432:5432"
    # The following turns the DB into less durable, but gains significant performance improvements for the tests run (x3
    # improvement on my personal machine). We should consider moving this into a dedicated Docker Compose configuration for
    # tests.
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  email:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped
  plywood:
    image: node:14.5.0-alpine
    working_dir: /app
    command: npm run watch-node
    ports:
      - "3000:3000"
      - "9231:9229"
    volumes:
      - ./plywood/server:/app
    environment:
      - LOG_MODE=request_and_response

