# This configuration file is for the **development** setup.
# For a production example please refer to kubernetes or CloudRun setups
version: "2.2"
x-redash-service: &redash-service
  build:
    context: .
    args:
      skip_frontend_build: "true"
  volumes:
    - .:/app
x-redash-environment: &redash-environment
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  REDASH_RATELIMIT_ENABLED: "false"
  REDASH_MAIL_DEFAULT_SENDER: "datareporter@example.com"
  REDASH_MAIL_SERVER: "email"
  REDASH_ENFORCE_CSRF: "false"
  MAILCHIMP_SERVER: "us1"
  MAILCHIMP_API_KEY: "e4c804be8fbd3c445a0fef9d05b6fc27"
  MAILCHIMP_LIST_ID: "e48180787b"
  REDASH_DEBUG: "false"
  CLIENT_TIMEOUT_DELTA: 30000
services:
  server:
    <<: *redash-service
    command: dev_server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
      - "5678:5678"
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
      PLYWOOD_SERVER_URL: "http://plywood:3000"
    volumes:
      - .:/app
  scheduler:
    <<: *redash-service
    command: dev_scheduler
    depends_on:
      - server
    environment:
      <<: *redash-environment
  worker-server:
    <<: *redash-service
    command: dev_worker_server
    ports:
      - "5001:5000"
    depends_on:
      - server
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
#  worker:
#    <<: *redash-service
#    command: dev_worker
#    depends_on:
#      - server
#    environment:
#      <<: *redash-environment
#      PYTHONUNBUFFERED: 0
  redis:
    image: redis:3-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  postgres:
    image: postgres:9.5-alpine
    # The following turns the DB into less durable, but gains significant performance improvements for the tests run (x3
    # improvement on my personal machine). We should consider moving this into a dedicated Docker Compose configuration for
    # tests.
    ports:
      - "15432:5432"
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  email:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
    restart: unless-stopped
  plywood:
    image: node:14.5.0-alpine
    working_dir: /app
    command: npm run watch-node
    ports:
      - "3000:3000"
      - "9231:9229"
    volumes:
      - ./plywood/server:/app
    environment:
      - LOG_MODE=request_and_response
