# This configuration file is for the **development** setup.
# For a production example please refer to getredash/setup repository on GitHub.
version: "2.2"
x-redash-service: &redash-service
  build:
    context: .
    args:
      skip_frontend_build: "true"
  volumes:
    - .:/app
  networks: 
    - drnetwork  
x-redash-environment: &redash-environment
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
  REDASH_RATELIMIT_ENABLED: "false"
  REDASH_MAIL_DEFAULT_SENDER: "redash@example.com"
  REDASH_MAIL_SERVER: "email"
  REDASH_ENFORCE_CSRF: "true"
services:
  server:
    <<: *redash-service
    command: dev_server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
      - "5678:5678"
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
      PLYWOOD_SERVER_URL: "http://localhost:3000"
    networks: 
      - drnetwork  
  scheduler:
    <<: *redash-service
    command: dev_scheduler
    depends_on:
      - server
    environment:
      <<: *redash-environment
    networks: 
      - drnetwork  
  worker:
    <<: *redash-service
    command: dev_worker
    depends_on:
      - server
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
    networks: 
      - drnetwork  
  redis:
    image: redis:3-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks: 
      - drnetwork
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks: 
      - drnetwork
  email:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
    restart: unless-stopped
    networks: 
      - drnetwork
networks:
  drnetwork:
      driver: bridge