[project]
id = "com.datareporter.server"
name = "Datareporter Server"
version = "0.0.1"

[build]
builder="paketobuildpacks/builder:full"
exclude = [
    ".build",
    "tests",
    "kubernetes",
    "setup",
    "client/node_modules",
    "plywood/server/node_modules",
    "plywood/server/client/node_modules"
]
[[build.env]]
name = 'BP_CPYTHON_VERSION'
value = '3.7.*' # any valid semver constraints (e.g. 3.10.2, 3.*) are acceptable
[[build.env]]
name = 'BP_NODE_VERSION'
value="12.18.3"

[[build.buildpacks]]
id='paketo-buildpacks/nodejs'
version = "1.1.0"
[[build.buildpacks]]
id='paketo-buildpacks/python'
version = "2.7.3"
[[processes]]
type = "web"
MAX_REQUESTS=1000
MAX_REQUESTS_JITTER=100
command="gunicorn -b 0.0.0.0:5000 --name redash -w${REDASH_WEB_WORKERS:-4} redash.wsgi:app --max-requests $MAX_REQUESTS --max-requests-jitter $MAX_REQUESTS_JITTER"
#default = true
