FROM cypress/browsers:node18.12.0-chrome106-ff106

ENV APP=/usr/src/app
WORKDIR $APP

COPY . .

# Debug: list contents of client folder after copy
RUN ls -la client
RUN ls -la client/cypress

WORKDIR $APP/client
RUN npm install

# Verify Cypress installation
RUN ./node_modules/.bin/cypress verify
