FROM cypress/browsers:chrome67

# Optional dependencies for GUI libs if needed for Cypress
# RUN apt-get update && apt-get install -y \
#     libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb \
#     && rm -rf /var/lib/apt/lists/*

ENV APP=/usr/src/app

# Create working directory
WORKDIR $APP
COPY . $APP

# Change to client directory and install deps
WORKDIR $APP/client
RUN ls
RUN npm install

# Copy the rest of the repo (if needed)

# Verify Cypress installation
RUN $APP/client/node_modules/.bin/cypress verify
