substitutions:
  _GCR_HOSTNAME: europe-west1-docker.pkg.dev
  _ENVIRONMENT:


steps:

  - name: gcr.io/cloud-builders/docker
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'PROJECT_ID=$PROJECT_ID'
      - '_GCR_HOSTNAME=$_GCR_HOSTNAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
    script: |
       #!/usr/bin/env bash
       docker buildx build \
       --push \
       -t $_GCR_HOSTNAME/$PROJECT_ID/datareporter/datareporter:$COMMIT_SHA \
       -t $_GCR_HOSTNAME/$PROJECT_ID/datareporter/datareporter:latest \
       -t $_GCR_HOSTNAME/$PROJECT_ID/datareporter/datareporter:$BRANCH_NAME \
       --build-arg version=$BRANCH_NAME-$COMMIT_SHA \
       --build-arg skip_dev_deps=true \
       -f Dockerfile -o type=image \
       .

    id: Build-Data-Reporter
    waitFor: [ '-' ]
  - name: gcr.io/cloud-builders/docker
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'
      - 'PROJECT_ID=$PROJECT_ID'
      - '_GCR_HOSTNAME=$_GCR_HOSTNAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
    script: |
      #!/usr/bin/env bash
      docker buildx build \
      --push \
      -t "$_GCR_HOSTNAME/$PROJECT_ID/datareporter/plywood:$COMMIT_SHA" \
      -t "$_GCR_HOSTNAME/$PROJECT_ID/datareporter/plywood:latest" \
      -t "$_GCR_HOSTNAME/$PROJECT_ID/datareporter/plywood:$BRANCH_NAME" \
      --build-arg "version=$BRANCH_NAME-$COMMIT_SHA" \
      -f Dockerfile -o type=image \
      .;

    dir: plywood/server
    id: Build-Plywood
    waitFor: [ '-' ]
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud builds triggers  run datareporter-deploy-$BRANCH_NAME
        --region=$LOCATION --branch=$BRANCH_NAME  --substitutions=_IMAGE_TAG="$COMMIT_SHA",
    id: Deploy-$BRANCH_NAME
    entrypoint: bash
    waitFor:
      - Build-Data-Reporter
      - Build-Plywood
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter/datareporter:$COMMIT_SHA'
  - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter/datareporter:latest'
  - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter/datareporter:$BRANCH_NAME'
  - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter/plywood:$COMMIT_SHA'
  - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter/plywood:$BRANCH_NAME'
  - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter/plywood:latest'
options:
  substitutionOption: ALLOW_LOOSE
