substitutions:
  _GCR_HOSTNAME: eu.gcr.io
  _ENVIRONMENT:


steps:

  - name: gcr.io/cloud-builders/docker
    script: |
       #!/usr/bin/env bash
       docker buildx create --use ;\
       docker buildx build \
       --cache-from "type=registry,ref=$_GCR_HOSTNAME/$PROJECT_ID/datareporter:cache-$BRANCH_NAME" \
       --cache-to "type=registry,ref=$_GCR_HOSTNAME/$PROJECT_ID/datareporter:cache-$BRANCH_NAME" \
       --push \
       -t $_GCR_HOSTNAME/$PROJECT_ID/datareporter:$COMMIT_SHA \
       -t $_GCR_HOSTNAME/$PROJECT_ID/datareporter:latest \
       --build-arg version=$BRANCH_NAME-$COMMIT_SHA \
       --build-arg skip_dev_deps=true \
       -f Dockerfile -o  type=image \
       .

    id: Build-Data-Reporter
    waitFor: [ '-' ]
  - name: gcr.io/cloud-builders/docker
    script: |
      #!/usr/bin/env bash
      docker buildx create --use ;\
      docker buildx build \
      --cache-from "type=registry,ref=$_GCR_HOSTNAME/$PROJECT_ID/plywood:cache-$BRANCH_NAME" \
      --cache-to "type=registry,ref=$_GCR_HOSTNAME/$PROJECT_ID/plywood:cache-$BRANCH_NAME" \
      --push \
      -t "$_GCR_HOSTNAME/$PROJECT_ID/plywood:$COMMIT_SHA" \
      -t "$_GCR_HOSTNAME/$PROJECT_ID/plywood:latest" \
      --build-arg "version=$BRANCH_NAME-$COMMIT_SHA" \
      -f Dockerfile -o type=image \
      .;

    dir: plywood/server
    id: Build-Plywood
    waitFor: [ '-' ]
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter:$COMMIT_SHA'
    id: Push-Data-Reporter
    waitFor:
      - Build-Data-Reporter
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud builds triggers  run datareporter-deploy-$BRANCH_NAME
        --region=$LOCATION --sha=$COMMIT_SHA --substitutions=_IMAGE_TAG="$COMMIT_SHA"
    id: Deploy-$BRANCH_NAME
    entrypoint: bash
    waitFor:
      - Build-Data-Reporter
      - Build-Plywood
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter:$COMMIT_SHA'
  - '$_GCR_HOSTNAME/$PROJECT_ID/plywood:$COMMIT_SHA'
  - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter:latest'
  - '$_GCR_HOSTNAME/$PROJECT_ID/plywood:latest'
options:
  substitutionOption: ALLOW_LOOSE
