substitutions:
  _GCR_HOSTNAME: eu.gcr.io
  _ENVIRONMENT:


steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - build
      - --build-arg
      - version=$COMMIT_SHA
      - --push
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter:$COMMIT_SHA'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter:latest'
      - .
      - '--build-arg'
      - 'skip_dev_deps=true'
      - '-f'
      - Dockerfile
      - '-o'
      - type=image
    id: Build-Data-Reporter
    waitFor: [ '-' ]
  - name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - build
      - --build-arg
      - version=$COMMIT_SHA
      - --push
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/plywood:$COMMIT_SHA'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/plywood:latest'
      - .
      - '-f'
      - Dockerfile
      - '-o'
      - type=image
    dir: plywood/server
    id: Build-Plywood
    waitFor: [ '-' ]
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter:$COMMIT_SHA'
    id: Push-Data-Reporter
    waitFor:
      - Build-Data-Reporter
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud builds triggers  run datareporter-deploy-$_ENVIRONMENT
        --region=$LOCATION --sha=$COMMIT_SHA --substitutions=_IMAGE_TAG="$COMMIT_SHA",_ENVIRONMENT=$_ENVIRONMENT
    id: Deploy-$_ENVIRONMENT
    entrypoint: bash
    waitFor:
      - Push-Data-Reporter
      - Push-Plywood
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter:$COMMIT_SHA'
  - '$_GCR_HOSTNAME/$PROJECT_ID/plywood:$COMMIT_SHA'
  - '$_GCR_HOSTNAME/$PROJECT_ID/datareporter:latest'
  - '$_GCR_HOSTNAME/$PROJECT_ID/plywood:latest'
options:
  substitutionOption: ALLOW_LOOSE
