steps:
  - name: 'bash'
    script: |
      #!/usr/bin/env bash
      rm -R  .pip-cache-build || true
      mkdir .pip-cache-build
      cp .gcloud/pip-cache.Dockerfile .pip-cache-build/Dockerfile
      cp requirements*txt .pip-cache-build/
      ls -l .pip-cache-build/

  - name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - build
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/pip-cache:$COMMIT_SHA'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/pip-cache:latest'
      - .
      - '-o'
      - type=image
    dir: .pip-cache-build
    id: Build-Pip-Cache

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/pip-cache:$COMMIT_SHA'
    id: Push-Pip-Cache
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/pip-cache:latest'
    id: Push-Pip-Cache-Latest


images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/pip-cache:$COMMIT_SHA'
  - '$_GCR_HOSTNAME/$PROJECT_ID/pip-cache:latest'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _GCR_HOSTNAME: eu.gcr.io
