substitutions:
  _GCR_HOSTNAME: eu.gcr.io
  _IMAGE_TAG: $COMMIT_SHA
  _ENVIRONMENT: $ENVIRONMENT
  _REGION: europe-west1
steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud secrets versions access latest
        --secret=kubeconfig-digitalocean-k8s  >
        /config/kubeconfig.conf
    entrypoint: bash
    volumes:
      - name: config
        path: /config
  - name: 'alpine/helm:3.11.1'
    env:
      - KUBECONFIG=/config/kubeconfig.conf
    args:
      - repo
      - add
      - datareporter
      - 'https://dataminelab.github.io/contrib-helm-chart/'
    id: Add-repo
    volumes:
      - name: config
        path: /config
  - name: 'alpine/helm:3.11.1'
    env:
      - KUBECONFIG=/config/kubeconfig.conf
    args:
      - '-n'
      - $_ENVIRONMENT
      - 'upgrade'
      - '--install'
      - '--reuse-values'
      - datareporter
      - datareporter/datareporter
      - '--set'
      - plywood.image.tag=$_IMAGE_TAG
      - '--set'
      - datareporter.image.tag=$_IMAGE_TAG
      - --timeout=15m
      - --atomic
    id: K8s-Deploy
    volumes:
      - name: config
        path: /config
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Upgrade-Datareporter-Server
    entrypoint: gcloud
    args: [ 'run', 'deploy', '$_ENVIRONMENT-datareporter-server', '--image', '$_GCR_HOSTNAME/$PROJECT_ID/datareporter:$_IMAGE_TAG' ,'--region',"$_REGION"]
    waitFor: [ 'K8s-Deploy' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Upgrade-Datareporter-Worker
    entrypoint: gcloud
    args: [ 'run', 'deploy', '$_ENVIRONMENT-datareporter-worker', '--image', '$_GCR_HOSTNAME/$PROJECT_ID/datareporter:$_IMAGE_TAG' ,'--region',"$_REGION"]
    waitFor: [ 'K8s-Deploy' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Upgrade-Plywood-Server
    entrypoint: gcloud
    args: [ 'run', 'deploy', '$_ENVIRONMENT-plywood-server', '--image', '$_GCR_HOSTNAME/$PROJECT_ID/plywood:$_IMAGE_TAG','--region',"$_REGION" ]
    waitFor: [ 'K8s-Deploy' ]
tags:
  - datareporter-server-$_ENVIRONMENT
