steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >-
        gcloud secrets versions access latest
        --secret=kubeconfig-k8s-1-25-4-do-0-fra1-1678526047017  >
        /config/kubeconfig.conf
    entrypoint: bash
    volumes:
      - name: config
        path: /config
  - name: 'alpine/helm:3.11.1'
    env:
      - KUBECONFIG=/config/kubeconfig.conf
    args:
      - repo
      - add
      - datareporter
      - 'https://dataminelab.github.io/contrib-helm-chart/'
    id: Add-repo
    volumes:
      - name: config
        path: /config
  - name: 'alpine/helm:3.11.1'
    env:
      - KUBECONFIG=/config/kubeconfig.conf
    args:
      - '-n'
      - $_ENVIRONMENT
      - 'upgrade'
      - '--install'
      - '--reuse-values'
      - datareporter
      - datareporter/datareporter
      - '--set'
      - plywood.image.tag=$_IMAGE_TAG
      - '--set'
      - datareporter.image.tag=$_IMAGE_TAG
      - --timeout=15m
      - --atomic
    id: Deploy
    volumes:
      - name: config
        path: /config
substitutions:
  _IMAGE_TAG: $COMMIT_SHA
  _ENVIRONMENT: $ENVIRONMENT
tags:
  - datareporter-server-$_ENVIRONMENT
