# This configuration file is for the **development** setup.
# For a production example please refer to kubernetes or CloudRun setups
x-redash-service: &redash-service
  build:
    context: ..
    tags:
      - ${TAG-latest}
    cache_from:
      - "eu.gcr.io/datareporter/datareporter:cache"
    cache_to:
      - "eu.gcr.io/datareporter/datareporter:cache"
    args:
      skip_frontend_build: "${skip_frontend_build-true}"
      skip_dev_deps: "${skip_dev_deps-false}"
      skip_ds_deps: "${skip_ds_deps-true}"
x-redash-environment: &redash-environment
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
services:
  datareporter:
    <<: *redash-service
    command: manage version
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
      - "5678:5678"
    environment:
      <<: *redash-environment
      REDASH_WORKER_NOTIFY_URL: "http://worker-server:5000/execute"
      PYTHONUNBUFFERED: 0
      PLYWOOD_SERVER_URL: "http://plywood:3000"
    volumes:
      - .:/app
  redis:
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  postgres:
    image: postgres:9.5-alpine
    ports:
      - "15432:5432"
      - "5432:5432"
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
  plywood:
    build:
      context: ../plywood/server
      tags:
        - ${TAG-latest}
      cache_from:
        - "eu.gcr.io/datareporter/plywood:cache"
      cache_to:
        - "eu.gcr.io/datareporter/plywood:cache"
    ports:
      - "3000:3000"
      - "9231:9229"
    environment:
      - LOG_MODE=request_and_response
