apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datareporter-frontend
spec:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datareporter-frontend
---
  apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: datareporter-backend
  spec:
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 60
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: datareporter-backend
  
