apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datareporter-web
spec:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datareporter-web
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datareporter-ad-hoc-worker
spec:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datareporter-ad-hoc-worker
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datareporter-scheduled-worker
spec:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datareporter-scheduled-worker
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datareporter-scheduler
spec:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datareporter-scheduler
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datareporter-lb
spec:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datareporter-lb
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: plywood-server
spec:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plywood-server
