apiVersion: v1
kind: Service
metadata:
  name: datareporter-web
spec:
  type: NodePort
  selector:
    app: datareporter
    tier: web
  ports:
    - name: dr-web
      port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-ad-hoc-worker
spec:
  type: NodePort
  selector:
    app: datareporter
    tier: ad-hoc-worker
  ports:
    - name: dr-worker
      port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-scheduled-worker
spec:
  type: NodePort
  selector:
    app: datareporter
    tier: scheduled-worker
  ports:
    - name: dr-worker
      port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-scheduler
spec:
  type: NodePort
  selector:
    app: datareporter
    tier: scheduler
  ports:
    - name: dr-worker
      port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-lb
spec:
  type: LoadBalancer
  selector:
    app: datareporter
    tier: lb
  ports:
    - name: dr-lb
      protocol: TCP
      port: 443
      targetPort: 80

