apiVersion: v1
kind: Service
metadata:
  name: datareporter-web
spec:
  type: NodePort
  selector:
    app: datareporter
    tier: web
  ports:
    - name: dr-web
      port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-worker
spec:
  type: NodePort
  selector:
    app: datareporter
    tier: worker
  ports:
    - name: dr-worker
      port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-lb
spec:
  type: LoadBalancer
  selector:
    app: datareporter
    tier: lb
  ports:
    - name: dr-lb
      port: 80

