"""empty message
Revision ID: 1916fbf3b1eb
Revises: b89fbc8cf4c1
Create Date: 2020-12-23 21:35:32.766354
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON

# revision identifiers, used by Alembic.
revision = '1916fbf3b1eb'
down_revision = 'b89fbc8cf4c1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('options', JSON(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###