"""empty message

Revision ID: 11e4489f2123
Revises: 20a3aed6b20e
Create Date: 2020-12-07 20:37:26.983840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e4489f2123'
down_revision = '20a3aed6b20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('table', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'table')
    # ### end Alembic commands ###
