"""empty message

Revision ID: 357f3783f705
Revises: 4697bc3b1bf9
Create Date: 2023-11-26 04:26:16.505961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357f3783f705'
down_revision = '4697bc3b1bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('api_key', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'api_key')
    # ### end Alembic commands ###
