"""empty message

Revision ID: 37b3afe90101
Revises: make_group_permissions_mutable
Create Date: 2026-02-23 21:43:49.949785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b3afe90101'
down_revision = 'make_group_permissions_mutable'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'type')
    # ### end Alembic commands ###
