"""empty message

Revision ID: 44b116635803
Revises: db238f81a5aa
Create Date: 2025-04-11 12:18:38.542360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b116635803'
down_revision = 'db238f81a5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reports_data_source_id_fkey', 'reports', type_='foreignkey')
    op.drop_column('reports', 'data_source_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('data_source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reports_data_source_id_fkey', 'reports', 'data_sources', ['data_source_id'], ['id'])
    # ### end Alembic commands ###
