"""empty message

Revision ID: 4697bc3b1bf9
Revises: a0bb29c2eb4c
Create Date: 2023-08-26 21:50:04.348712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4697bc3b1bf9'
down_revision = 'a0bb29c2eb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('tags', postgresql.ARRAY(sa.Unicode()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'tags')
    # ### end Alembic commands ###
