"""empty message

Revision ID: 4fd85b6d30f2
Revises: 37b3afe90101
Create Date: 2026-03-16 20:11:26.957840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fd85b6d30f2'
down_revision = '37b3afe90101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column(
        'reports',
        sa.Column('schedule_failures', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    op.alter_column('reports', 'schedule_failures', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'schedule_failures')
    op.drop_column('reports', 'schedule')
    # ### end Alembic commands ###
