"""empty message

Revision ID: 96ba629490dd
Revises: 2118f5874142
Create Date: 2024-12-21 09:18:15.515444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ba629490dd'
down_revision = '2118f5874142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('last_modified_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reports', 'users', ['last_modified_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'last_modified_by_id')
    # ### end Alembic commands ###
