"""empty message

Revision ID: a0bb29c2eb4c
Revises: 11e4489f2123
Create Date: 2023-08-24 18:11:40.739550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0bb29c2eb4c'
down_revision = '11e4489f2123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_reports_is_archived'), 'reports', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_is_archived'), table_name='reports')
    op.drop_column('reports', 'is_archived')
    # ### end Alembic commands ###
