"""empty message

Revision ID: a813195c3fb2
Revises: b89fbc8cf4c1
Create Date: 2024-07-26 12:07:47.314184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, JSON
import redash

# revision identifiers, used by Alembic.
revision = 'a813195c3fb2'
down_revision = 'b89fbc8cf4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('alerts', 'options',
                existing_type=JSON(astext_type=sa.Text()),
                type_=JSONB(astext_type=sa.Text()),
                nullable=True,
                postgresql_using='options::jsonb',
                )
    op.alter_column('changes', 'change',
               existing_type=sa.TEXT(),
               type_=JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='change::jsonb')
    op.alter_column('dashboards', 'layout',
               existing_type=sa.TEXT(),
               type_=JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='layout::jsonb')
    op.alter_column('events', 'additional_properties',
               existing_type=sa.TEXT(),
               type_=JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='additional_properties::jsonb')
    op.add_column('notification_destinations', sa.Column('encrypted_options', redash.models.types.EncryptedConfiguration(), nullable=False))
    op.drop_column('notification_destinations', 'options')
    op.alter_column('organizations', 'settings',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('queries', 'schedule',
                existing_type=sa.Text(),
                type_=JSONB(astext_type=sa.Text()),
                nullable=True,
                postgresql_using='schedule::jsonb',
                )
    op.alter_column('queries', 'options',
                existing_type=JSON(astext_type=sa.Text()),
                type_=JSONB(astext_type=sa.Text()),
                nullable=True,
                postgresql_using='options::jsonb',
                )
    op.alter_column('query_results', 'data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'details',
               existing_type=JSONB(astext_type=sa.Text()),
               type_=JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_column('users', 'profile_image_url')
    op.alter_column('visualizations', 'options',
                existing_type=JSON(astext_type=sa.Text()),
                type_=JSONB(astext_type=sa.Text()),
                nullable=True,
                postgresql_using='options::jsonb',
                )
    op.alter_column('widgets', 'options',
                existing_type=JSON(astext_type=sa.Text()),
                type_=JSONB(astext_type=sa.Text()),
                nullable=True,
                postgresql_using='options::jsonb',
                )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('widgets', 'options',
               existing_type=JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('visualizations', 'options',
               existing_type=JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=False)
    op.add_column('users', sa.Column('profile_image_url', sa.VARCHAR(length=320), autoincrement=False, nullable=True))
    op.alter_column('users', 'details',
               existing_type=JSONB(astext_type=sa.Text()),
               type_=JSON(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('query_results', 'data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('queries', 'options',
               existing_type=JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('queries', 'schedule',
               existing_type=JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('organizations', 'settings',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('notification_destinations', sa.Column('options', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('notification_destinations', 'encrypted_options')
    op.alter_column('events', 'additional_properties',
               existing_type=JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('dashboards', 'layout',
        existing_type=sa.Text(),
        type_=JSONB(astext_type=sa.Text()),
        postgresql_using='layout::jsonb',
        )
    op.drop_column('dashboards', 'options')
    op.alter_column('changes', 'change',
               existing_type=JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('alerts', 'options',
               existing_type=JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
