"""empty message

Revision ID: febb1459b2c2
Revises: db238f81a5aa
Create Date: 2025-04-11 15:26:07.935791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febb1459b2c2'
down_revision = 'db238f81a5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('data_source_id', sa.Integer()))
    op.create_foreign_key(None, 'reports', 'data_sources', ['data_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'data_source_id')
    # ### end Alembic commands ###
