apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareporter-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareporter-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareporter-ad-hoc-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareporter-scheduled-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareporter-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareporter-plywood-server