apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datareporter-web
spec:
  minReplicas: 1
  maxReplicas: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datareporter-worker
spec:
  minReplicas: 1
  maxReplicas: 1
---
  apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: datareporter-lb
  spec:
    minReplicas: 1
    maxReplicas: 1
  