apiVersion: v1
kind: Service
metadata:
  name: datareporter-web  
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-worker
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-lb
