apiVersion: v1
kind: Service
metadata:
  name: datareporter-web  
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-ad-hoc-worker
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-scheduled-worker
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-lb
---
apiVersion: v1
kind: Service
metadata:
  name: datareporter-plywood-server
