apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareporter-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareporter-web
spec:
  template:
    spec:
      containers:
      - name: datareporter-web
        image: eu.gcr.io/datareporter/datareporter:_
        env:
          - name: REDASH_DATABASE_URL
            value: "postgresql://datareporter-staging:$(POSTGRES_PASSWORD)@private-db-postgresql-fra1-redash-do-user-3899788-0.b.db.ondigitalocean.com:25060/datareporter-staging?sslmode=require"
          - name: REDASH_REDIS_URL
            value: "rediss://default:$(REDIS_PASSWORD)@private-db-redis-fra1-46025-do-user-3899788-0.b.db.ondigitalocean.com:25061/0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareporter-worker
spec:
  template:
    spec:
      containers:
      - name: datareporter-worker
        image: eu.gcr.io/datareporter/datareporter:_
        env:
          - name: REDASH_DATABASE_URL
            value: "postgresql://datareporter-staging:$(POSTGRES_PASSWORD)@private-db-postgresql-fra1-redash-do-user-3899788-0.b.db.ondigitalocean.com:25060/datareporter-staging?sslmode=require"
          - name: REDASH_REDIS_URL
            value: "rediss://default:$(REDIS_PASSWORD)@private-db-redis-fra1-46025-do-user-3899788-0.b.db.ondigitalocean.com:25061/0"
          - name: WORKERS_COUNT
            value: "1"
