apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: datareporter
spec:
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: datareporter
