#!/bin/bash -eu

echo "Compiling..."

rm -rf build/*
mkdir -p build

node_modules/.bin/tdi -q # not everyone has the latest npm

echo "Compiling PEG.js"
/bin/sh ./compile-pegjs

echo "Compiling TypeScript"
/bin/sh ./compile-tsc
