name: Push to GCR GitHub Action
on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build-and-push-to-gcr-service-account:
    name: Build & push - with service account
    runs-on: ubuntu-latest
    steps:
      - name: Building and pushing the image
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          gcloud_service_key: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }} # <- not needed when used with google-github-actions/auth@v0
          registry: gcr.io
          project_id: datareporter
          image_name: eu.gcr.io/datareporter/datareporter
          image_tag: test-${{ github.sha }}, ${{ github.sha }}
          dockerfile: ./Dockerfile
          context: ./
          target: build
  # test-images:
  #   name: Test images from registry
  #   needs: 
  #     - build-and-push-to-gcr-workload-identity
  #     - build-and-push-to-gcr-service-account
  #     - build-and-push-to-gcr-without-gcloud-auth-action
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix: 
  #       type: [0, 1, 2]
  #   steps:
  #     - name: Authenticate to Google Cloud
  #       uses: google-github-actions/auth@v0
  #       with:
  #         credentials_json: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}
  #     - name: Testing the image
  #       run: |
  #         cat ${GOOGLE_APPLICATION_CREDENTIALS} | docker login -u _json_key --password-stdin gcr.io
  #         exit $([ "$(docker run gcr.io/pro-chesta/hello-world-by-push-to-gcr-${{ matrix.type }}:${{ github.sha }})" = "Hello World from Push To GCR github action" ])
