name: Pre-merge CI
on:
  workflow_call:
#  pull_request:
#    branches:
#      - develop

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  unit_tests:
    uses: ./.github/workflows/test-unit.yaml
    secrets: inherit
