name: Release docker Image
on:
  push:
    branches:
      - develop
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
#  unit_tests:
#    uses: ./.github/workflows/test-unit.yaml
#    secrets: inherit
  release_image:
    runs-on: ubuntu-latest
#    needs:
#      - unit_tests
    steps:
      - id: get-version
        run: |
          #!/bin/bash
          next_version=$(./.github/scripts/next_version.sh)
          echo "Next version: $next_version"
          echo "version=$next_version" >> $GITHUB_OUTPUT


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GCR_URL }}
          username: ${{ secrets.GCR_USERNAME }}
          password: ${{ secrets.GCR_PASSWORD }}
      - name: Build and push datareporter
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.GCR_URL }}/datareporter:${{ needs.get-version.outputs.version }}
      - name: Build and push datareporter
        uses: docker/build-push-action@v6
        with:
          push: true
          context: plywood/server
          tags: ${{ secrets.GCR_URL }}/plywood:${{ needs.get-version.outputs.version }}
